const store = require('../../utils/store.js'); const cloudStore = require('../../utils/cloud-store.js')
Page({
  data: { displayName: '', avatarUrl: '', publicId: '', unread: 0, unreadMessages: 0, followingCount: 0, followerCount: 0, sleepTarget: 8, movementTarget: 30, customGoals: [], newGoalName: '', newGoalValue: '', newGoalUnit: '次', sleepOptions: [6,7,8,9,10], movementOptions: [10,20,30,45,60], showProfileEditor: false, showGoals: false },
  onShow() { const { profile } = store.ensureState(); this.setData({ displayName: profile.displayName, avatarUrl: profile.avatarUrl || profile.cloudAvatarUrl || '', publicId: profile.publicId || '', sleepTarget: profile.sleepTarget, movementTarget: profile.movementTarget, customGoals: profile.customGoals || [] }); this.syncProfile(); this.syncSocial() },
  async syncSocial() { try { const result = await cloudStore.socialHub('stats'); this.setData({ followingCount: result.followingCount || 0, followerCount: result.followerCount || 0, unreadMessages: result.unreadMessages || 0 }) } catch (error) { console.warn('社交数据暂未同步', error) } },
  goConnections(event) { wx.navigateTo({ url: '/pages/connections/index?type=' + (event.currentTarget.dataset.type || 'following') }) },
  goMessages() { wx.navigateTo({ url: '/pages/messages/index' }) },
  goMyForum() { wx.navigateTo({ url: '/pages/my-forum/index' }) },
  async syncProfile() { const profile = store.ensureState().profile; try { const result = await cloudStore.bootstrapUser({ displayName: profile.displayName, avatarUrl: profile.cloudAvatarUrl || '' }); store.update(state => { state.profile.publicId = result.profile.publicId }); this.setData({ publicId: result.profile.publicId, unread: result.unread || 0 }) } catch (error) { console.warn('用户云资料尚未连接', error) } },
  setName(event) { this.setData({ displayName: event.detail.value }) }, toggleProfileEditor() { this.setData({ showProfileEditor: !this.data.showProfileEditor }) }, toggleGoals() { this.setData({ showGoals: !this.data.showGoals }) },
  chooseAvatar(event) { const tempFilePath = event.detail.avatarUrl; if (!tempFilePath) return; wx.getFileSystemManager().saveFile({ tempFilePath, success: result => this.persistAvatar(result.savedFilePath), fail: () => this.persistAvatar(tempFilePath) }) },
  persistAvatar(avatarUrl) { this.setData({ avatarUrl }); store.update(state => { state.profile.avatarUrl = avatarUrl }); this.uploadAvatar(avatarUrl); wx.showToast({ title: '头像已更新' }) },
  async uploadAvatar(filePath) { try { const result = await wx.cloud.uploadFile({ cloudPath: `avatars/${Date.now()}-${Math.random().toString(36).slice(2,8)}.jpg`, filePath }); store.update(state => { state.profile.cloudAvatarUrl = result.fileID }); await this.syncProfile() } catch (error) { console.warn('头像云端同步失败', error) } },
  saveNickname() { const displayName = this.data.displayName.trim() || 'SUTA 用户'; store.update(state => { state.profile.displayName = displayName }); this.setData({ displayName, showProfileEditor: false }); this.syncProfile(); wx.showToast({ title: '昵称已保存' }) },
  setSleep(event) { this.setData({ sleepTarget: this.data.sleepOptions[Number(event.detail.value)] }) }, setMovement(event) { this.setData({ movementTarget: this.data.movementOptions[Number(event.detail.value)] }) }, setNewGoalName(event) { this.setData({ newGoalName: event.detail.value }) }, setNewGoalValue(event) { this.setData({ newGoalValue: event.detail.value }) }, setNewGoalUnit(event) { this.setData({ newGoalUnit: event.detail.value }) },
  addCustomGoal() { const name = this.data.newGoalName.trim(); const target = Number(this.data.newGoalValue); const unit = this.data.newGoalUnit.trim(); if (!name || target <= 0 || !unit) return wx.showToast({ title: '请填写完整目标', icon: 'none' }); this.setData({ customGoals: [...this.data.customGoals, { id: `goal-${Date.now()}`, name, target, unit }], newGoalName: '', newGoalValue: '', newGoalUnit: '次' }) },
  removeCustomGoal(event) { this.setData({ customGoals: this.data.customGoals.filter(item => item.id !== event.currentTarget.dataset.id) }) }, saveGoals() { store.update(state => { state.profile.sleepTarget = this.data.sleepTarget; state.profile.movementTarget = this.data.movementTarget; state.profile.customGoals = this.data.customGoals }); this.setData({ showGoals: false }); wx.showToast({ title: '健康目标已保存' }) },
  goWallet() { wx.navigateTo({ url: '/pages/wallet/index' }) }, goSettings() { wx.navigateTo({ url: '/pages/settings/index' }) }, goLegal(event) { wx.navigateTo({ url: `/pages/legal/index?type=${event.currentTarget.dataset.type}` }) },
  exportData() { const content = JSON.stringify({ schemaVersion: 3, exportedAt: new Date().toISOString(), data: store.ensureState() }, null, 2); const filePath = `${wx.env.USER_DATA_PATH}/SUTA-健康数据-${Date.now()}.json`; wx.getFileSystemManager().writeFile({ filePath, data: content, encoding: 'utf8', success: () => { if (wx.shareFileMessage) wx.shareFileMessage({ filePath, fileName: 'SUTA-健康数据.json', fail: () => wx.setClipboardData({ data: content }) }); else wx.setClipboardData({ data: content }) }, fail: () => wx.showToast({ title: '导出失败', icon: 'none' }) }) }
  ,logout() {
    wx.showModal({ title: '退出当前账号？', content: '退出会清除这台设备上的本地打卡和个人设置；已经发布到云端的论坛帖子不会自动删除。', confirmText: '确认退出', confirmColor: '#cf6266', success: result => { if (!result.confirm) return; wx.removeStorageSync(store.KEY); store.ensureState(); wx.reLaunch({ url: '/pages/home/index' }) } })
  }
})
